import CardBox from "@/app/components/shared/CardBox";
import React, { useState } from "react";
import SocialButtons from "../../authforms/SocialButtons";
import AuthLogin from "../../authforms/AuthLogin";
import Link from "next/link";
import type { Metadata } from "next";
import { useRouter } from "next/router";
import FullLogo from "@/app/components/shared/logo/FullLogo";
export const metadata: Metadata = {
  title: "Boxed Login Authentication",
  description: "Generated by create next app",
};
const BoxedLogin = () => {

  return (
    <>
      <div className="relative overflow-hidden h-screen bg-lightprimary dark:bg-darkprimary">
        <div className="flex h-full justify-center items-center px-4">
          <CardBox className="md:w-[450px] w-full border-none">
            <div className="mx-auto mb-6">
              <h2 className="text-2xl">ระบบรายงานการฝึกงาน</h2>
            </div>
            <p className="text-center">กรอกรหัสนักศึกษา วัน/เดือน/ปีเกิด เพื่อเข้าสู่ระบบ</p>
            <AuthLogin />
            {/* <div className="flex gap-2 text-base text-ld font-medium mt-6 items-center justify-center">
              <p>New to Modernize?</p>
              <Link
                href={"/auth/auth2/register"}
                className="text-primary text-sm font-medium"
              >
                Create an account
              </Link>
            </div> */}
          </CardBox>
        </div>
      </div>
    </>
  );
};

export default BoxedLogin;
