import React from "react";
import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "@/lib/dateConfig";
const kanit = Kanit({ subsets: ["latin", "thai"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });
import "./css/globals.css";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import customTheme from "@/utils/theme/custom-theme";
import { CustomizerContextProvider } from "@/app/context/CustomizerContext";
import '../utils/i18n';
import NextTopLoader from 'nextjs-toploader';
import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "Modernize - Nextjs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  
  return (

    <html lang="th">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <ThemeModeScript />
      </head>
      <body className={`${kanit.className}`}>
      
        <Flowbite theme={{ theme: customTheme }}>
          <CustomizerContextProvider>
          <NextTopLoader color="var(--color-primary)" />
            <Providers>
               {children}
            </Providers>
          </CustomizerContextProvider>
        </Flowbite>
      </body>
    </html>

  );
}



